include ../Makefile.env

TARGET = cl_hello

SRCS = 
SRCS += main.c
SRCS += ../common/util_cl.c

OBJS =
OBJS += $(SRCS:%.c=./%.o)

INCLUDES += -I../common/

CFLAGS   +=

LDFLAGS  +=

include ../Makefile.include
